Document: generate-fru-storage
Title: Debian generate-fru-storage Manual
Author: <insert document author here>
Abstract: This manual describes what generate-fru-storage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/generate-fru-storage/generate-fru-storage.sgml.gz

Format: postscript
Files: /usr/share/doc/generate-fru-storage/generate-fru-storage.ps.gz

Format: text
Files: /usr/share/doc/generate-fru-storage/generate-fru-storage.text.gz

Format: HTML
Index: /usr/share/doc/generate-fru-storage/html/index.html
Files: /usr/share/doc/generate-fru-storage/html/*.html
